apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-backend-service
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
    component: backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
